# ==========================
# Project Settings
# ==========================

# プロジェクトルート
BASE_DIR="/mnt/c/DEV/SQLStudy"

# ==========================
# Log Settings
# ==========================

# ログ保存先
LOG_DIR="${BASE_DIR}/logs"

# ログの保持数
LOG_COUNT=30

# ログのファイル名

SQL_LOG_PREFIX="sql_exec"
SHELL_LOG_PREFIX="shell_exec"

